apiVersion: apps/v1
kind: Deployment
metadata:
  name: protfolio-local
spec:
  replicas: 0
  selector:
    matchLabels:
      app: k8s-demo
  template:
    metadata:
      labels:
        app: k8s-demo
    spec:
      containers:
        - name: vite-app
          image: mallubeast/k8s-demo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "16Mi"
              cpu: "1m"
            limits:
              memory: "32Mi" # A safe middle-ground
              cpu: "10m"
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-demo-service
spec:
  type: LoadBalancer
  selector:
    app: k8s-demo
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
